services:
  api:
    build: ./api
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
      - minio
    environment:
      - MONGO_URI=mongodb://mongodb:27017/mydatabase
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=yft76wefwfa4w6f&FI
      - MINIO_SECRET_KEY=yft76wefwfa4w6f1FI
    volumes:
      - ./api:/app
      - ./minio_data:/minio_data
      - ./scripts/init_minio.py:/app/init_minio.py
    command: sh -c "python init_minio.py && python app.py"

  mongodb:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./init_mongo.js:/docker-entrypoint-initdb.d/init_mongo.js
    # Da inserire per ricaricare tutto il db, o eliminare il volume su docker
    #   - ./init_mongo.js:/init_mongo.js
    # entrypoint: ["/bin/sh", "-c", "mongod --fork --logpath /var/log/mongodb.log --bind_ip_all && mongosh < /init_mongo.js && tail -f /var/log/mongodb.log"]



  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_BASICAUTH_USERNAME=yft76wefwfa4w6f1FI
      - ME_CONFIG_BASICAUTH_PASSWORD=yft76wefwfa4w6f1FI

  minio:
    image: minio/minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ACCESS_KEY=yft76wefwfa4w6f1FI
      - MINIO_SECRET_KEY=yft76wefwfa4w6f1FI
    command: server /data --console-address ":9001"
    # volumes:
    #   - minio_data:/data


volumes:
  mongodb_data:
  minio_data:
